ACCOUNT_NAME: 洪佳桂
ACCOUNT_NUMBER: 6226220634022296
ADMANAGE_FILE_SAVE_PATH: /data/nfsshare/upload/picture
AD_FILE_MAX_SIZE: 2048000
AD_FILE_SAVE_PATH: /data/nfsshare/upload/ad
AD_SUPPORT_FILE_TYPE: .jpg|.jpeg|.gif|.bmp|.png
AGRICULTURAL_BANK_SMS_PATH: /data/nfsshare/upload/agricultural_bank_sms
APP_EDITION_SERVICE_IP: https://file-uat.qifenqian.com/pic/
CERTIFY_FILE_MAX_SIZE: 5120000
CERTIFY_FILE_SAVE_PATH: /data/nfsshare/upload/certify
CERTIFY_SUPPORT_FILE_TYPE: .jpg|.jpeg|.gif|.bmp|.png
CF_FILE_SAVE_PATH: /data/nfsshare/upload/certificate
CHANNEL_NAME: yyt
DUBBO_CONFIG_IP: zookeeper://192.168.1.14:2181
EXCEL_FILE_SAVE_PATH: /data/nfsshare/upload/payment
EXPORT_EXCEL: /data/nfsshare/upload/excel
FM_PROD_CHECK_FILE: D:/data/nfsshare/combined/fm
GATEWAY:
    CHANNEL:
        IP: http://localhost:10024
    KINGDEE:
        IP: http://localhost:15300
    UNIO:
        IP: http://localhost:9001
IDENTITY_FILE_SAVE_PATH: /data/nfsshare/upload/identity
IMAGEIP: localhost
IMG_FILE_PATH: /data/nfsshare/upload/headimg
JGKJ_FILE_PATH: /data/nfsshare/upload/yintong
LOG:
    BASEDIR: /data/STC_BMS/logs
    LEVEL: DEBUG
MERCHANT_CODE: INNER_EPAY_7777777
MQ_URL: failover:(tcp://192.168.1.17:61616,tcp://192.168.1.18:61616)?randomize=false&amp;backup=true&amp;priorityBackup=true
PERSON_FILE_SAVE_PATH: /data/nfsshare/upload/person
PRODUCET_FILE_SAVE_PATH: /data/nfsshare/upload/producet
REDIS:
    AUTH: pass123
    IP: 192.168.1.19
    PORT: 6379
SERVICE_IP: https://www.qifenqian.com
SERVICE_IP_TEST: https://183.11.223.2:7443
SKIP_FILTER_IP: 127.0.0.1#192.168.1.16#192.168.1.15
SX_FILE_SAVE_PATH: /data/nfsshare/upload/vbill/
SYSTEM:
    CORE:
        IP: http://localhost:1234
    PLUGIN:
        IP: http://localhost:5002
UNIONPAY_FILE_PATH: /data/nfsshare/upload/unionpay
VERSION: v1.0.0
channelMerchantid: Z0000842
images:
    absolutePaths: /data/nfsshare/upload/picture
ip:
    white:
        list: 127.0.0.1#192.168.1.16#192.168.1.15
mybatis:
    config-location: classpath:/mybatis/MyBatisMapConfig.xml
spring:
    datasource:
        combinedmaster:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: combinedpayment
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.17:3306/combinedpayment?zeroDateTimeBehavior=convertToNull
            username: combinedpayment
            validationQuery: select 1
        combinedslave:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: combinedpayment
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.18:3306/combinedpayment?zeroDateTimeBehavior=convertToNull
            username: combinedpayment
            validationQuery: select 1
        driverClassName: com.mysql.jdbc.Driver
        sabs:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: 123456
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.17:3306/sabs?zeroDateTimeBehavior=convertToNull
            username: sabs_user
            validationQuery: select 1
        stcdb:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: 123456
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.17:3306/stcdb?zeroDateTimeBehavior=convertToNull
            username: stc_web_user
            validationQuery: select 1
        stcdbslave:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: 123456
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.18:3306/stcdb?zeroDateTimeBehavior=convertToNull
            username: stc_web_user
            validationQuery: select 1
        stcs:
            initialSize: 1
            maxActive: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            password: 123456
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.17:3306/stcs?zeroDateTimeBehavior=convertToNull
            username: stcs_user
            validationQuery: select 1
        type: com.alibaba.druid.pool.DruidDataSource
system:
    sevenmall: http://192.168.1.15:5001/sevenmall
    sevenpay: http://192.168.1.15:5005/sevenpay
