dubbo:
   application:
      name: jellyfish
      qosEnable: false
   scan:
      basePackages: com.qifenqian.jellyfish
   registry:
      id: jellyfish-registry
      address: ${dubbo.registry.url}
   protocol:
      id: jellyfish
      port: 21803
      startus: server
   provider:
      filter: IPauthority
      cluster: failfast
      
endpoints:
   dubbo:
      enabled: false
