spring:
   mvc:
      view:
         prefix: /views/
         suffix: .jsp
server:
   port: 80
spring:
   profiles:
      active: '@spring.profiles.active@'
   main:
      allow-bean-definition-overriding: true
